create table master_agama(
kode_agama CHARACTER VARYING(255) NOT NULL UNIQUE PRIMARY KEY,
nama CHARACTER VARYING(50) NOT NULL UNIQUE,
deskripsi CHARACTER VARYING(255),
created_date TIMESTAMP NOT NULL, 
created_by CHARACTER VARYING(50) NOT NULL
);

